/*=========================================================================================
  File Name: moduleEmailState.js
  Description: Email Module State
  ----------------------------------------------------------------------------------------
  Item Name: Vuexy - Vuejs, HTML & Laravel Admin Dashboard Template
  Author: Pixinvent
  Author URL: http://www.themeforest.net/user/pixinvent
==========================================================================================*/


export default {
  mails: [
    {
      id: 1,
      inquiry: 'Bitte beschreiben Sie kurz Ihr Forschungsprojekt und erläutern Sie den Zweck der zu entwickelnden Mensch-Technik-Interaktion.',
      subject: 'Frage-ID 001',
      message: '<p> </p>',
      isStarred: false,
      labels: ['Allgemein'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: "text",
        options: [],
        answer: '',
      },
      remark: '',
    },
    {
      id: 2,
      inquiry: 'Beschreiben Sie kurz, welche Interaktionen die Maschine mit Menschen ausführen soll?',
      subject: 'Frage-ID 002',
      message: '<p></p>',
      isStarred: false,
      labels: ['Allgemein'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: "text",
        options: [],
        answer: '',
      },
      remark: '',
    },
    {
      id: 3,
      inquiry: 'Wem soll das Forschungsergebnis dienen?',
      subject: 'Frage-ID 003',
      message: '<p> z. B. der gesamten Gesellschaft oder einer bestimmten Teilgruppe der Gesellschaft. </p>',
      isStarred: false,
      labels: ['Allgemein'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: "bigtext",
        options: [],
        answer: '',
      },
      remark: '',
    },
    {
      id: 5,
      inquiry: 'Hilft oder dient das System bzw. Forschungsergebnis einer schutzbedürftigen Gruppe?',
      subject: 'Frage-ID 005',
      message: '<p><a @click.prevent="$emit('kblink', {id: 29})">"Zur Definition einer Künstlichen Intelligenz."</a></p>',
      isStarred: false,
      labels: ['Allgemein'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: "followup-radio",
        options: [
          {name: 'Ja', followupID: 5.1, risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
        ],

        answer: '',
      },
      remark: '',
    },
    {
      id: 5.1,
      inquiry: 'Ist die betroffene schutzbedürftige Gruppe direkt in das Forschungsprojekt involviert?',
      subject: 'Frage-ID 005.1',
      message: '<p></p>',
      isStarred: false,
      labels: ['Allgemein'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: "radio",
        options: [
          {name: 'Ja', risk_contemplation: 0, risk_existence: 0, risk_addressing: 1},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 6,
      inquiry: 'Ist ein Einsatz oder Vertrieb der Mensch-Technik-Interaktion in der Privatwirtschaft oder der öffentlichen Verwaltung nach Abschluss des Forschungsprojektes geplant?',
      subject: 'Frage-ID 006',
      message: '<p></p>',
      isStarred: false,
      labels: ['Allgemein'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: "radio",
        options: [
          {name: 'Ja', risk_contemplation: 0, risk_existence: 1, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 7,
      inquiry: 'Handelt es sich bei der Mensch-Technik-Interaktion um eine Künstliche Intelligenz?',
      subject: 'Frage-ID 101',
      message: '<p><a @click.prevent="$emit('kblink', {id: 2})">"Zur Definition einer Künstlichen Intelligenz."</a></p>',
      isStarred: false,
      labels: ['Allgemein'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: "followup-radio",
        options: [
          {name: 'Ja', followupID: 7.1, risk_contemplation: 0, risk_existence: 1, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
        ],

        answer: '',
      },
      remark: '',
    },
    {
      id: 7.1,
      inquiry: 'Beschreiben Sie bitte kurz die Funktionsweise der Künstlichen Intelligenz.',
      subject: 'Frage-ID 101.1',
      message: `<p></p>`,
      isStarred: false,
      labels: ['Allgemein'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: "text",
        options: [],
        answer: '',
      },
      remark: '',
    },
    {
      id: 8,
      inquiry: 'Könnte die Künstliche Intelligenz Einfluss auf Entscheidungen haben, die einen oder mehrere Menschen benachteiligen?',
      subject: 'Frage-ID 102',
      message: '<p></p>',
      isStarred: false,
      labels: ["Allgemein"],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: "followup-radio",
        options: [
          {name: 'Ja', followupID: 8.1, risk_contemplation: 0, risk_existence: 1, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
        ],

        answer: '',
      },
      remark: '',
    },
    {
      id: 8.1,
      inquiry: 'Sind technische Maßnahmen geplant, die eine mögliche Benachteiligung ausschließen oder minimieren?',
      subject: 'Frage-ID 102.1',
      message: '<p></p>',
      isStarred: false,
      labels: ["Allgemein"],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: "radio",
        options: [
          {name: 'Ja', risk_contemplation: 0, risk_existence: 0, risk_addressing: 1},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 9,
      inquiry: 'Ist die Künstliche Intelligenz vom Entwickler jederzeit übersteuerbar?.',
      subject: 'Frage-ID 103',
      message: '<p></p>',
      isStarred: false,
      labels: ['Allgemein'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: "followup-radio",
        options: [
          {name: 'Ja', followupID: 9.1 , risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
          {name: 'Nein', followupID: 9.2, risk_contemplation: 0, risk_existence: 1, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 9.1,
      inquiry: 'Wie stellen Sie die Übersteuerbarkeit der Künstlichen Intelligenz sicher?',
      subject: 'Frage-ID 103.1',
      message: '<p></p>',
      isStarred: false,
      labels: ['Allgemein', 'Autonomie'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: "text",
        options: [],
        answer: '',
      },
      remark: '',
    },
    {
      id: 9.2,
      inquiry: 'Lässt sich die fehlende Übersteuerbarkeit nachvollziehbar begründen?',
      subject: 'Frage-ID 103.2',
      message: '<p></p>',
      isStarred: false,
      labels: ['Allgemein', 'Autonomie'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 0, risk_existence: 0, risk_addressing: 1},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 10,
      inquiry: 'Ist die Künstliche Intelligenz vom Anwender jederzeit übersteuerbar?',
      subject: 'Frage-ID 104',
      message: '<p></p>',
      isStarred: false,
      labels: ['Allgemein', 'Autonomie','Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'followup-radio',
        options: [
          {name: 'Ja', followupID: 10.1, risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
          {name: 'Nein', followupID: 10.2, risk_contemplation: 0, risk_existence: 1, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 10.1,
      inquiry: 'Wie stellen Sie die Übersteuerbarkeit der Künstlichen Intelligenz durch den Anwender sicher?',
      subject: 'Frage-ID 104.1',
      message: '<p></p>',
      isStarred: false,
      labels: ['Allgemein', 'Autonomie','Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: "text",
        options: [],
        answer: '',
      },
      remark: '',
    },
    {
      id: 10.2,
      inquiry: 'Lässt sich nachvollziehbar begründen, weshalb der Anwender die Künstliche Intelligenz nicht übersteuern können muss?',
      subject: 'Frage-ID 104.2',
      message: '<p></p>',
      isStarred: false,
      labels: ['Allgemein', 'Autonomie','Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 0, risk_existence: 0, risk_addressing: 1},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 11,
      inquiry: 'Ist sichergestellt, dass die Repräsentativität in Hinblick auf (Trainings-)Daten gewährleistet ist?',
      subject: 'Frage-ID 201',
      message: '<p>Sog. BIAS-Vermeidung: <a @click.prevent="$emit('kblink', {id: 20})">"Zur Definition eines BIAS."</a></p>',
      isStarred: false,
      labels: ['Allgemein', 'Autonomie'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', followupID: 18.1, risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 1, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 12,
      inquiry: 'Wie werden die Daten innerhalb Ihres Forschungsprojektes auf mögliche BIAS geprüft?',
      subject: 'Frage-ID 202',
      message: '<p></p>',
      isStarred: false,
      labels: ['Allgemein', 'Autonomie'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: "text",
        options: [],
        answer: '',
      },
      remark: '',
    },    
    {
      id: 20,
      inquiry: 'Werden durch das zu entwickelnde Produkt personenbezogene Daten verarbeitet?',
      subject: 'Frage-ID 0020',
      message: '<p>Zur Definition von "personenbezogenen Daten" nach der DSGVO: <a href="https://eur-lex.europa.eu/legal-content/DE/TXT/HTML/?uri=CELEX:32016R0679&from=DE#d1e1508-1-1" target="_blank">personenbezogene Daten</a>  </p>',
      isStarred: false,
      labels: ['Allgemein', 'Datenschutz', 'Schadensvermeidung','Autonomie','Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      // Filter: Optional array of objects
      filter: [
        {
          title: 'Ja',
          includes: [
            'Allgemein',
            'Datenschutz'
          ],
          active: false
        },
        {
          title: 'nein',
          includes: [
            'Allgemein',
          ],
          excludes: [
            'Datenschutz',
          ],
          active: false
        },
      ],
      answer: {
        type: 'filter',
        options: [
          {name: 'Ja', risk_contemplation: 1, risk_existence: 1, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 1, risk_existence: 0, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 13,
      inquiry: 'Sind Teile oder Aufgaben im Projekt an Dritte ausgelagert ("outgesourced")?',
      subject: 'Frage-ID 203',
      message: '<p></p>',
      isStarred: false,
      labels: ['Datenschutz', 'Schadensvermeidung','Autonomie','Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'followup-radio',
        options: [
          {name: 'Ja', followupID: 13.1, risk_contemplation: 0, risk_existence: 1, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 13.1,
      inquiry: 'Können Sie die Repräsentativität der Daten im outgesourcten Teil sicherstellen?',
      subject: 'Frage-ID 203.1',
      message: '<p></p>',
      isStarred: false,
      labels: ['Datenschutz','Schadensvermeidung','Autonomie','Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 0, risk_existence: 0, risk_addressing: 1},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 14,
      inquiry: 'Sollen sämtliche Datenzugriffe im Forschungsprojekt schriftlich dokumentiert werden?',
      subject: 'Frage-ID 204',
      message: '<p></p>',
      isStarred: false,
      labels: ['Datenschutz', 'Schadensvermeidung','Autonomie','Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 1, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 15,
      inquiry: 'Wird im Forschungsprojekt geprüft, ob Faktoren wie Alter, Geschlecht, sozialer Hintergrund und Diversität zielgruppengerecht in den (Trainings-)Daten abgebildet werden?',
      subject: 'Frage-ID 205',
      message: '<p></p>',
      isStarred: false,
      labels: ['Datenschutz', 'Schadensvermeidung','Autonomie','Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 1, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 16,
      inquiry: 'Gibt es unter den Entwickelnden der Mensch-Technik-Interaktion eine ausreichende Diversität (Geschlecht, Alter, Herkunft etc.)?',
      subject: 'Frage-ID 206',
      message: '<p></p>',
      isStarred: false,
      labels: ['Datenschutz', 'Schadensvermeidung','Autonomie','Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 1, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 17,
      inquiry: 'Werden Anwendende informiert, wenn eine signifikante Entscheidung über sie von der Künstlichen Intelligenz getroffen oder unterstützt wurde?',
      subject: 'Frage-ID 301',
      message: '<p></p>',
      isStarred: false,
      labels: ['Datenschutz', 'Schadensvermeidung','Autonomie','Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 1, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 18,
      inquiry: 'Kann das System kontinuierlich aktualisiert werden (z. B. durch Updates)?',
      subject: 'Frage-ID 302',
      message: '<p></p>',
      isStarred: false,
      labels: ['Datenschutz', 'Schadensvermeidung','Autonomie','Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'followup-radio',
        options: [
          {name: 'Ja', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
          {name: 'Nein', followupID: 18.1, risk_contemplation: 0, risk_existence: 1, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 18.1,
      inquiry: 'Gibt es nachvollziehbare Gründe, die eine regelmäßige Aktualisierung nicht notwendig machen?',
      subject: 'Frage-ID 302.1',
      message: '<p></p>',
      isStarred: false,
      labels: ['Datenschutz', 'Schadensvermeidung','Autonomie','Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 0, risk_existence: 0, risk_addressing: 1},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 19,
      inquiry: 'Kann die Funktionsfähigkeit der Künstlichen Intelligenz regelmäßig überprüft werden?',
      subject: 'Frage-ID 303',
      message: '<p></p>',
      isStarred: false,
      labels: ['Datenschutz', 'Schadensvermeidung','Autonomie','Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 1, risk_existence: 0, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 1, risk_existence: 1, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 21,
      inquiry: 'Wird sichergestellt, dass die Entwickelnden die Funktionsweise des Algorithmus vollständig nachvollziehen können?',
      subject: 'Frage-ID 304',
      message: '<p><a @click.prevent="$emit('kblink', {id: 4})">"Zur Definition eines Algorithmus."</a></p>',
      isStarred: false,
      labels: ['Datenschutz', 'Schadensvermeidung','Autonomie','Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 1, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 22,
      inquiry: 'Besteht ein realistisches Risiko, dass eine mangelnde Nachvollziehbarkeit der Funktionsweise Schaden versursachen kann?',
      subject: 'Frage-ID 305',
      message: '<p></p>',
      isStarred: false,
      labels: ['Datenschutz', 'Schadensvermeidung','Autonomie','Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'followup-radio',
        options: [
          {name: 'Ja', followupID: 22.1, risk_contemplation: 0, risk_existence: 1, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 22.1,
      inquiry: 'Ergreifen Sie Maßnahmen, um das Risiko technisch und/oder organisatorisch so gering wie möglich zu halten?',
      subject: 'Frage-ID 305.1',
      message: '<p></p>',
      isStarred: false,
      labels: ['Datenschutz', 'Schadensvermeidung','Autonomie','Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 0, risk_existence: 0, risk_addressing: 1},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 23,
      inquiry: 'Ist sichergestellt, dass die Funktionsweise der Künstlichen Intelligenz dem Anwendenden (Laien/Nicht-Programmierenden) erklärbar gemacht werden kann?',
      subject: 'Frage-ID 306',
      message: '<p></p>',
      isStarred: false,
      labels: ['Datenschutz', 'Schadensvermeidung','Autonomie','Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'followup-radio',
        options: [
          {name: 'Ja', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
          {name: 'Nein', followupID: 23.1, risk_contemplation: 0, risk_existence: 1, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 23.1,
      inquiry: 'Gibt es einen nachvollziehbaren Grund, weshalb die Funktionsweise der Künstlichen Intelligenz für den Anwender nicht erklärbar gemacht werden muss?',
      subject: 'Frage-ID 306.1',
      message: '<p></p>',
      isStarred: false,
      labels: ['Datenschutz', 'Schadensvermeidung','Autonomie','Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 0, risk_existence: 0, risk_addressing: 1},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 24,
      inquiry: 'Besteht ein realistisches Risiko, dass durch eine mangelnde Erklärbarkeit für Anwendende ein Schaden entstehen kann?',
      subject: 'Frage-ID 307',
      message: '<p></p>',
      isStarred: false,
      labels: ['Datenschutz', 'Schadensvermeidung','Autonomie','Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'followup-radio',
        options: [
          {name: 'Ja', folloupID: 24.1, risk_contemplation: 0, risk_existence: 1, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 1, risk_existence: 0, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 24.1,
      inquiry: 'Ergreifen Sie Maßnahmen, um das Risiko technisch und/oder organisatorisch so gering wie möglich zu halten?',
      subject: 'Frage-ID 307.1',
      message: '<p></p>',
      isStarred: false,
      labels: ['Datenschutz', 'Schadensvermeidung','Autonomie','Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 0, risk_existence: 0, risk_addressing: 1},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 25,
      inquiry: 'Soll der Quellcode des entwickelten Algorithmus bzw. die Funktionsweise der Künstlichen Intelligenz öffentlich zugänglich gemacht oder auf Nachfrage erhältlich sein?',
      subject: 'Frage-ID 308',
      message: '<p></p>',
      isStarred: false,
      labels: ['Datenschutz', 'Schadensvermeidung','Autonomie','Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'followup-radio',
        options: [
          {name: 'Ja', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
          {name: 'Nein', followupID: 25.1, risk_contemplation: 0, risk_existence: 1, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 25.1,
      inquiry: 'Existieren nachvollziehbare Gründe, die einer möglichen Veröffentlichung entgegenstehen?',
      subject: 'Frage-ID 308.1',
      message: '<p></p>',
      isStarred: false,
      labels: ['Datenschutz', 'Schadensvermeidung','Autonomie'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 0, risk_existence: 0, risk_addressing: 1},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
          ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 26,
      inquiry: 'Kann bei falschen Entscheidungen oder Ergebnissen der Künstlichen Intelligenz nachvollzogen werden, welche Schlüsselfaktoren zu der falschen Entscheidung bzw. dem falschen Ergebnis geführt haben?',
      subject: 'Frage-ID 309',
      message: '<p> </p>',
      isStarred: false,
      labels: ['Datenschutz', 'Schadensvermeidung','Autonomie'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 1, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 27,
      inquiry: 'Ist es möglich, dass das Forschungsergebnis von Dritten für ethisch unterwünschte Zwecke missbraucht werden kann?',
      subject: 'Frage-ID 401',
      message: '<p><a @click.prevent="$emit('kblink', {id: 4})">"Zur Definition von Dual Use."</a></p>',
      isStarred: false,
      labels: ['Datenschutz', 'Schadensvermeidung','Autonomie','Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 0, risk_existence: 1, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 28,
      inquiry: 'Interagiert das System physisch mit der Welt?',
      subject: 'Frage-ID 402',
      message: '<p></p>',
      isStarred: false,
      labels: ['Datenschutz', 'Schadensvermeidung','Autonomie','Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'followup-radio',
        options: [
          {name: 'Ja', followupID: 28.1, risk_contemplation: 0, risk_existence: 1, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
          ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 28.1,
      inquiry: 'Kann das System physische Schäden verursachen?',
      subject: 'Frage-ID 402.1',
      message: '<p></p>',
      isStarred: false,
      labels: ['Datenschutz', 'Schadensvermeidung','Autonomie','Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 0, risk_addressing: 1},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 29,
      inquiry: 'Wird im Projektverlauf über mögliche Schäden, die die Mensch-Technik-Interaktion auslösen kann, nachgedacht?',
      subject: 'Frage-ID 403',
      message: '<p></p>',
      isStarred: false,
      labels: ['Datenschutz', 'Autonomie','Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'followup-radio',
        options: [
          {name: 'Ja', followupID: 29.1, risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 1, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 29.1,
      inquiry: 'Werden mögliche Auswirkungen der Mensch-Technik-Interaktion in einer Technikfolgenabschätzung untersucht?',
      subject: 'Frage-ID 403.1',
      message: '<p> </p>',
      isStarred: false,
      labels: ['Allgemein', 'Autonomie'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 0, risk_existence: 0, risk_addressing: 1},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
          ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 30,
      inquiry: 'Existiert für die Mensch-Technik-Interaktion im Projektverlauf ein regelmäßiger, standardisierter Prüfzyklus?',
      subject: 'Frage-ID 404',
      message: '<p> </p>',
      isStarred: false,
      labels: ['Allgemein', 'Autonomie','Gerechtigkeit','Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'followup-radio',
        options: [
          {name: 'Ja', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
          {name: 'Nein', followupID: 30.1, risk_contemplation: 0, risk_existence: 1, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 30.1,
      inquiry: 'Gibt es im Projekt andere Maßnahmen, die die Qualität der Mensch-Technik-Interaktion sicherstellen können?',
      subject: 'Frage-ID 404.1',
      message: '<p></p>',
      isStarred: false,
      labels: ['Allgemein', 'Autonomie','Gerechtigkeit','Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 0, risk_existence: 0, risk_addressing: 1},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 31,
      inquiry: 'Ist das Projektteam über ethische Grundsätze der Entwicklung von Mensch-Technik-Interaktionen informiert?',
      subject: 'Frage-ID 405',
      message: '<p> </p>',
      isStarred: false,
      labels: ['Allgemein', 'Schadensvermeidung','Autonomie','Gerechtigkeit'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 1, risk_addressing: 0},
          ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 32,
      inquiry: 'Gibt es im Projekt einen Verantwortlichen, der sich möglicher Beschwerden zu falschen bzw. unfairen Entscheidungen der Mensch-Technik-Interaktion annimmt?',
      subject: 'Frage-ID 406',
      message: '<p></p>',
      isStarred: false,
      labels: ['Allgemein', 'Schadensvermeidung','Autonomie','Gerechtigkeit'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 1, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 33,
      inquiry: 'Ist die zu entwickelnde Mensch-Technik-Interaktion in der praktischen Anwendung geeignet, Ergebnisse oder Daten zu liefern, die gegen Gleichheitsgrundsätze verstoßen könnten?',
      subject: 'Frage-ID 407',
      message: '<p><a @click.prevent="$emit('kblink', {id: 4})">"Zu Gleichheitsgrundsätzen nach Art. 3 GG."</a></p>',
      isStarred: false,
      labels: ['Allgemein', 'Fürsorge','Schadensvermeidung','Gerechtigkeit'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 0, risk_existence: 1, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id:34,
      inquiry: 'Kann die Mensch-Technik-Interaktion dazu geeignet sein, weitere Rechte Dritter zu tangieren oder hierin einzugreifen?',
      subject: 'Frage-ID 408',
      message: '<p><a @click.prevent="$emit('kblink', {id: 4})">"Zur Drittwirkung von Grundrechten."</a></p>',
      isStarred: false,
      labels: ['Allgemein', 'Fürsorge','Schadensvermeidung','Gerechtigkeit'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'followup-radio',
        options: [
          {name: 'Ja', followupID: 34.1, risk_contemplation: 0, risk_existence: 1, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 34.1,
      inquiry: 'Welche Grundrechte könnten hier betroffen sein?',
      subject: 'Frage-ID 408.1',
      message: '<p></p>',
      isStarred: false,
      labels: ['Allgemein', 'Fürsorge','Schadensvermeidung','Autonomie','Gerechtigkeit'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: "text",
        options: [],
        answer: '',
      },
      remark: '',
    },
    {
      id: 35,
      inquiry: 'Werden in der Entwicklung der Mensch-Technik-Interaktion die Grundsätze von Privacy-by-Design und Privacy-by-Default berücksichtigt??',
      subject: 'Frage-ID 409',
      message: '<p>Zu <a @click.prevent="$emit('kblink', {id: 17})">"Privacy by Design."</a> und <a @click.prevent="$emit('kblink', {id: 18})">"Privacy by Default."</a></p>',
      isStarred: false,
      labels: ['Allgemein', 'Fürsorge','Schadensvermeidung'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 1, risk_addressing: 0},
          ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 36,
      inquiry: 'Werden in der Entwicklung der Mensch-Technik-Interaktion die Grundsätze von Ethics-by-Design berücksichtigt?',
      subject: 'Frage-ID 410',
      message: '<p><a @click.prevent="$emit('kblink', {id: 17})">"Zur Definition von Ethics-by-Design."</a></p>',
      isStarred: false,
      labels: ['Allgemein', 'Fürsorge','Schadensvermeidung'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 1, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 37,
      inquiry: 'Werden in der Entwicklung der Mensch-Technik-Interaktion der Grundsatz und das Ideal der "digitalen Barrierefreiheit" berücksichtigt?',
      subject: 'Frage-ID 411',
      message: '<p><a @click.prevent="$emit('kblink', {id: 21})">"Zur Definition von digitaler Barrierefreiheit."</a></p>',
      isStarred: false,
      labels: ['Allgemein', 'Fürsorge','Schadensvermeidung','Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 1, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 38,
      inquiry: 'Könnte Sie Technologie missbraucht werden, um das Vertrauen in soziale oder gesellschaftliche Institutionen zu schädigen?',
      subject: 'Frage-ID 412',
      message: '<p> z. B. Medien, Medizinbereich, Regierungsbehörden etc. </p>',
      isStarred: false,
      labels: ['Allgemein', 'Fürsorge','Schadensvermeidung','Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 0, risk_existence: 1, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 39,
      inquiry: 'Könnte die Technologie missbraucht werden, um anderen Menschen Schaden zuzufügen oder illegale Aktivitäten zu fördern?',
      subject: 'Frage-ID 413',
      message: '<p>z. B. Stalking, Mobbing, Finanzbetrug, Diebstahl etc. </p>',
      isStarred: false,
      labels: ['Allgemein', 'Schadensvermeidung','Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 0, risk_existence: 1, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 40,
      inquiry: 'Gibt es Bevölkerungsgruppen, die aufgrund Ihrer sozialen Herkunft oder finanziell verfügbaren Mitteln von der Nutzung der Mensch-Technik-Interaktion ausgeschlossen sein könnten?',
      subject: 'Frage-ID 414',
      message: '<p></p>',
      isStarred: false,
      labels: ['Allgemein', 'Schadensvermeidung','Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 0, risk_existence: 1, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 58,
      inquiry: 'Handelt es sich bei dem zu entwickelnden Produkt um ein System, welches ggfs. innerhalb Kritischer Infrastrukturen (sog. KRITIS, z.B. IT/TK, Energie, Wasser, Ernährung, Transport/Verkehr, Gesundheit, Finanz-/Versicherungswesen) eingesetzt wird oder werden kann?',
      subject: 'Frage-ID 0058',
      message: '<p>Zur Definition von Kritischen Infrastrukturen: <a href="https://www.gesetze-im-internet.de/bsig_2009/__8b.html" target="_blank">"Kritischer Infrastrukturen" </a>   </p>',
      isStarred: false,
      labels: ['Allgemein', 'Fürsorge','Schadensvermeidung','Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'followup-radio',
        options: [
          {name: 'Ja', followupID: 58.1, risk_contemplation: 1, risk_existence: 1, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 1, risk_existence: 0, risk_addressing: 0},
          ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 58.1,
      inquiry: 'Sind Ihnen die hiermit verbundenen Rechte und Pflichten des Bundesamtes bzw. des Betreibers (z.B. §§ 7a, 8a, 8b BSIG) bekannt?',
      subject: 'Frage-ID 0058.1',
      message: '<p></p>',
      isStarred: false,
      labels: ['Allgemein', 'Fürsorge','Schadensvermeidung','Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 0, risk_existence: 0, risk_addressing: 1},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 60,
      inquiry: 'Enthält das zu entwickelnde Produkt eigenständig technische Maßnahmen/Vorkehrungen zur Schadensvermeidung nach dem "Stand der Technik" (z.B. Aufzeichnungs-, Melde- oder Informationsvorgänge)?',
      subject: 'Frage-ID 0060',
      message: '<p></p>',
      isStarred: false,
      labels: ['Allgemein', 'Fürsorge','Schadensvermeidung','Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 61,
      inquiry: 'Handelt es sich bei dem zu entwickelnden Produkt um einen "digitalen Dienst" i.S.v. § 8c BSIG?',
      subject: 'Frage-ID 0061',
      message: '<p></p>',
      isStarred: false,
      labels: ['Allgemein', 'Fürsorge','Schadensvermeidung','Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'followup-radio',
        options: [
          {name: 'Ja', followupID: 61.1, risk_contemplation: 1, risk_existence: 1, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 1, risk_existence: 0, risk_addressing: 0},
          ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 61.1,
      inquiry: 'Sind die besonderen Anforderungen an deren Anbieter bekannt?',
      subject: 'Frage-ID 0061.1',
      message: '<p>Zu den Anforderungen an Anbieter: <a href="https://www.gesetze-im-internet.de/bsig_2009/__8c.html" target="_blank">"Anbieter" </a>  </p>',
      isStarred: false,
      labels: ['Allgemein', 'Fürsorge','Schadensvermeidung','Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 0, risk_existence: 0, risk_addressing: 1},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 63,
      inquiry: 'Ist bekannt, dass nicht nur das übermäßiges Sammeln und Verarbeiten von Daten, sondern auch das rechtswidrige Löschen oder Vernichten von Daten Straftatbestände erfüllen kann?',
      subject: 'Frage-ID 0063',
      message: '<p>Zur Definition von übermäßigem Sammeln und Verarbeiten von Daten: <a href="https://www.gesetze-im-internet.de/stgb/__202a.html" target="_blank">übermäßige Sammeln und Verarbeiten von Daten </a>, zum rechtswidrigen Löschen oder Vernichten von Daten: <a href="https://www.gesetze-im-internet.de/stgb/__303a.html" target="_blank">Löschen oder Vernichten von Daten </a>   </p>',
      isStarred: false,
      labels: ['Allgemein', 'Fürsorge','Schadensvermeidung'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 1, risk_existence: 0, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 1, risk_existence: 1, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 64,
      inquiry: 'Ist bekannt, dass eine bzgl. Datensicherheit schlecht oder unzureichend gestaltete Software oder Anwendung Schadensersatzansprüche auslösen kann, die sich auch auf sog. Folgeschäden erstrecken können?',
      subject: 'Frage-ID 0064',
      message: '<p>Zu möglichen Schadensersatzansprüchen:<a href="https://www.gesetze-im-internet.de/bgb/__823.html">Schadensersatzansprüche </a>, Zur Definition von Folgeschäden: <a href="https://www.gesetze-im-internet.de/prodhaftg/__1.html">"Folgeschäden" </a> </p>',
      isStarred: false,
      labels: ['Allgemein', 'Schadensvermeidung','Autonomie','Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 1, risk_existence: 0, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 1, risk_existence: 1, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 65,
      inquiry: 'Ist bekannt, dass der Grundsatz der "Sicherheit der Verarbeitung" auch in der DSGVO normiert ist und dort durch weitere Vorgaben konkretisiert wird (Art. 5 Abs. 1 lit. f i.V.m. Art. 32 DSGVO)?',
      subject: 'Frage-ID 0065',
      message: '<p></p>',
      isStarred: false,
      labels: ['Allgemein', 'Fürsorge','Schadensvermeidung','Autonomie','Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 1, risk_existence: 0, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 1, risk_existence: 1, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 66,
      inquiry: 'Untersuchen und beurteilen Sie die Qualität der verwendeten Datenquellen?',
      subject: 'Frage-ID 0066',
      message: '<p></p>',
      isStarred: false,
      labels: ['Allgemein', 'Schadensvermeidung','Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'followup-radio',
        options: [
          {name: 'Ja', followupID: 66.1, risk_contemplation: 1, risk_existence: 0, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 1, risk_existence: 1, risk_addressing: 0},
          ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 66.1,
      inquiry: 'Wie stellen Sie die Herkunft und Qualität der verwendeten Daten sicher?',
      subject: 'Frage-ID 0066.1',
      message: '<p></p>',
      isStarred: false,
      labels: ['Allgemein', 'Schadensvermeidung','Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 0, risk_existence: 0, risk_addressing: 1},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 68,
      inquiry: 'Planen Sie, die Kompetenzen der Mitarbeiter im Projekt im Bereich Datenschutz zu berücksichtigen und zu erweitern?',
      subject: 'Frage-ID 0068',
      message: '<p></p>',
      isStarred: false,
      labels: ['Allgemein', 'Schadensvermeidung','Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 1, risk_existence: 0, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 1, risk_existence: 1, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 69,
      inquiry: 'Sollen interne/externe Datenzugriffe im Projekt dokumentiert werden?',
      subject: 'Frage-ID 0069',
      message: '<p></p>',
      isStarred: false,
      labels: ['Allgemein', 'Schadensvermeidung','Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'text',
        options: [],
        answer: '',
      },
      remark: '',
    },
    {
      id: 70,
      inquiry: 'Arbeiten Sie mit bereits vorhandenen Datensätzen?',
      subject: 'Frage-ID 0070',
      message: '<p></p>',
      isStarred: false,
      labels: ['Allgemein', 'Schadensvermeidung'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 1, risk_existence: 1, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 1, risk_existence: 1, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 71,
      inquiry: 'Interagiert das System physisch mit der Welt?',
      subject: 'Frage-ID 0071',
      message: '<p></p>',
      isStarred: false,
      labels: ['Allgemein', 'Schadensvermeidung'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'followup-radio',
        options: [
          {name: 'Ja', followupID: 71.1, risk_contemplation: 1, risk_existence: 1, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 1, risk_existence: 0, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 71.1,
      inquiry: 'Welche physischen Schäden kann das System verursachen?',
      subject: 'Frage-ID 0071.1',
      message: '<p></p>',
      isStarred: false,
      labels: ['Allgemein', 'Schadensvermeidung'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 0, risk_existence: 0, risk_addressing: 1},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 73,
      inquiry: 'Kann das System kontinuierlich aktualisiert werden (Updates)?',
      subject: 'Frage-ID 0073',
      message: '<p></p>',
      isStarred: false,
      labels: ['Allgemein', 'Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 1, risk_existence: 1, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 1, risk_existence: 1, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 74,
      inquiry: 'Sind Teile ihres Projekts outgesourced?',
      subject: 'Frage-ID 0074',
      message: '<p></p>',
      isStarred: false,
      labels: ['Allgemein', 'Schadensvermeidung','Autonomie'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'followup-radio',
        options: [
          {name: 'Ja', followupID: 74.1, risk_contemplation: 1, risk_existence: 1, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 1, risk_existence: 0, risk_addressing: 0},
          ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 74.1,
      inquiry: 'Planen Sie die Qualität der Daten und deren Sicherheit im outgesourcten Teil sicherzustellen (vgl. Art. 28 DSGVO)?',
      subject: 'Frage-ID 0074.1',
      message: '<p></p>',
      isStarred: false,
      labels: ['Allgemein', 'Schadensvermeidung','Autonomie'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 0, risk_existence: 0, risk_addressing: 1},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 76,
      inquiry: 'Verwenden Sie externe Software/Quellcode/Daten?',
      subject: 'Frage-ID 0076',
      message: '<p></p>',
      isStarred: false,
      labels: ['Allgemein', 'Schadensvermeidung','Autonomie'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 1, risk_existence: 1, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 1, risk_existence: 0, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 79,
      inquiry: 'Kann die Funktionsfähigkeit (Zuverlässigkeit der Ergebnisse) des Systems regelmäßig überprüft werden?',
      subject: 'Frage-ID 0079',
      message: '<p></p>',
      isStarred: false,
      labels: ['Allgemein', 'Schadensvermeidung','Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 1, risk_existence: 0, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 1, risk_existence: 1, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 80,
      inquiry: 'Ist es vorstellbar, das System für ethisch unerwünschte Zwecke zu entfremden (Dual Use, z. B. LAWS) ?',
      subject: 'Frage-ID 0080',
      message: '<p>Definition <a @click.prevent="$emit(\'kblink\', {id: 8})">"Dual Use"</a>.</p>',
      isStarred: false,
      labels: ['Allgemein', 'Schadensvermeidung'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 1, risk_existence: 1, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 1, risk_existence: 0, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 81,
      inquiry: 'Wäre es für den Antragsteller denkbar, dass eine vollständige Erklärbarkeit und Transparenz des Algorithmus nicht sicher dargestellt werden kann?',
      subject: 'Frage-ID 0081',
      message: '<p></p>',
      isStarred: false,
      labels: ['Allgemein', 'Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'followup-radio',
        options: [
          {name: 'Ja', followupID: 81.1, risk_contemplation: 1, risk_existence: 1, risk_addressing: 0},
          {name: 'Nein', followupID: 81.2, risk_contemplation: 1, risk_existence: 0, risk_addressing: 0},
          ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 81.2,
      inquiry: 'Können Sie den Algorithmus bzw. das Ergebnis des Algorithmus dem Anwender (Laien/Nicht-Programmierer) erklärbar und transparent machen?',
      subject: 'Frage-ID 0081.2',
      message: '<p></p>',
      isStarred: false,
      labels: ['Allgemein', 'Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 0, risk_existence: 0, risk_addressing: 1},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 81.1,
      inquiry: 'Ergreifen Sie Maßnahmen, um das Risiko technisch und/oder organisatorisch so gering wie möglich zu halten?',
      subject: 'Frage-ID 0081.1',
      message: '<p></p>',
      isStarred: false,
      labels: ['Allgemein', 'Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 0, risk_existence: 0, risk_addressing: 1},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
        ],
      },
      remark: '',
    },
    {
      id: 84,
      inquiry: 'Ist sichergestellt, dass die Angemessenheit und Repräsentativität in Hinblick auf (Trainings-)Daten gewährleistet ist (sog. BIAS-Vermeidung)?',
      subject: 'Frage-ID 0084',
      message: '<p>Zur Definition von BIAS: <a @click.prevent="$emit(\'kblink\', {id: 20})">BIAS</a></p>',
      isStarred: false,
      labels: ['Allgemein', 'Gerechtigkeit'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'followup-radio',
        options: [
          {name: 'Ja', risk_contemplation: 1, risk_existence: 0, risk_addressing: 0},
          {name: 'Nein', followupID: 84.1, risk_contemplation: 1, risk_existence: 1, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 84.1,
      inquiry: 'Ergreifen Sie Maßnahmen, mit denen eine bessere Datenqualität hergestellt werden?',
      subject: 'Frage-ID 0084.1',
      message: '<p></p>',
      isStarred: false,
      labels: ['Allgemein', 'Gerechtigkeit'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 0, risk_existence: 0, risk_addressing: 1},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
        ],
      },
      remark: '',
    },
    {
      id: 86,
      inquiry: 'Wäre es technisch möglich, den Code Ihres Algorithmus öffentlich darstellbar und zugänglich zu machen?',
      subject: 'Frage-ID 0086',
      message: '<p></p>',
      isStarred: false,
      labels: ['Allgemein', 'Transparenz'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 1, risk_existence: 0, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 1, risk_existence: 0, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 87,
      inquiry: 'Soll im Projektverlauf eine Technikfolgenabschätzung erfolgen?',
      subject: 'Frage-ID 0087',
      message: '<p></p>',
      isStarred: false,
      labels: ['Allgemein', 'Fürsorge','Schadensvermeidung'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'followup-radio',
        options: [
          {name: 'Ja', followupID: 87.1, risk_contemplation: 1, risk_existence: 0, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 1, risk_existence: 1, risk_addressing: 0},
          ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 87.1,
      inquiry: 'Welche Bereiche müsste eine Technikfolgenabschätzung umfassen? (Gesellschaft, Umwelt etc.)',
      subject: 'Frage-ID 0087.1',
      message: '<p></p>',
      isStarred: false,
      labels: ['Allgemein', 'Fürsorge','Schadensvermeidung'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 0, risk_existence: 0, risk_addressing: 1},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 89,
      inquiry: 'Sind Mechanismen geplant, die im Falle eines Schadens Abhilfe schaffen, z.B. in Form eines Rechtsschutzes oder einer Versicherungspolice?',
      subject: 'Frage-ID 0089',
      message: '<p> </p>',
      isStarred: false,
      labels: ['Allgemein', 'Schadensvermeidung'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'followup-radio',
        options: [
          {name: 'Ja', followupID: 89.1, risk_contemplation: 1, risk_existence: 0, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 1, risk_existence: 1, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },

    {
      id: 89.1,
      inquiry: 'Welche Mechanismen sollen diese Abhilfe konkret schaffen?',
      subject: 'Frage-ID 0089.1',
      message: '<p></p>',
      isStarred: false,
      labels: ['Allgemein','Schadensvermeidung'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 0, risk_existence: 0, risk_addressing: 1},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },

    {
      id: 91,
      inquiry: 'Halten Sie es für möglich, dass das zu entwickelnde Produkt - abgesehen von Gleichheitsgrundsätzen - weitere (Grund-)Rechte Dritter tangiert oder gar in diese eingegriffen werden könnte (sog. "Drittwirkung" von Grundrechten)?',
      subject: 'Frage-ID 0091',
      message: '<p></p>',
      isStarred: false,
      labels: ['Allgemein', 'Fürsorge','Schadensvermeidung','Autonomie','Gerechtigkeit'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'followup-radio',
        options: [
          {name: 'Ja', followupID: 91.1, risk_contemplation: 1, risk_existence: 1, risk_addressing: 0},
          {name: 'Nein', risk_contemplation: 1, risk_existence: 0, risk_addressing: 0},
          ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 91.1,
      inquiry: 'Welche Grundrechte könnten hierbei betroffen sein (z.B. Art. 2, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 16a, 21 GG)?',
      subject: 'Frage-ID 0091.1',
      message: '<p></p>',
      isStarred: false,
      labels: ['Allgemein', 'Fürsorge','Schadensvermeidung','Autonomie','Gerechtigkeit'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'radio',
        options: [
          {name: 'Ja', risk_contemplation: 0, risk_existence: 0, risk_addressing: 1},
          {name: 'Nein', risk_contemplation: 0, risk_existence: 0, risk_addressing: 0},
        ],
        answer: '',
      },
      remark: '',
    },
    {
      id: 93,
      inquiry: 'Welche (technisch-organisatischen) Maßnahmen werden getroffen, um mögliche Eingriffe zu minimieren?',
      subject: 'Frage-ID 0093',
      message: '<p></p>',
      isStarred: false,
      labels: ['Allgemein', 'Fürsorge','Schadensvermeidung','Autonomie','Gerechtigkeit'],
      time: '',
      folder: 'inbox',
      isTrashed: false,
      trashingReason: '',
      answer: {
        type: 'text',
        options: [],
        answer: '',
      },
      remark: '',
    },
  ],

  // Tags and labels
  mailTags: [
    {text: 'Allgemein', value: 'Allgemein', color: '#5E5E5F'},
    {text: 'Datenschutz', value: 'Datenschutz', color: '#5E5E5F'},
    {text: 'Tue Gutes', value: 'Fürsorge', color: '#333333'},
    {text: 'Tue niemandem weh', value: 'Schadensvermeidung', color: '#333333'},
    {text: 'Bewahre die menschliche Handlungsfähigkeit', value: 'Autonomie', color: '#333333'},
    {text: 'Sei fair', value: 'Gerechtigkeit', color: '#333333'},
    {text: 'Funktioniere', value: 'Transparenz', color: '#333333'},
  ],

  // Sidebar-filter for state (inbox, answered) and labels.
  mail_filter: null,
  meta: {},
  project: {
    nameApplicant: '',
    nameProject: '',
  },
  mailSearchQuery: '',
}

